<?php

namespace App\Enums;

enum AuditEventType: string
{
    case CANCELLATION_CREATED = 'CANCELLATION_CREATED';
    case RADICADO_GENERATED = 'RADICADO_GENERATED';
    case CANCELLATION_UPDATED = 'CANCELLATION_UPDATED';
    case OWNER_REASSIGNED = 'OWNER_REASSIGNED';
    case RADICADO_SMS_RETRY_REQUESTED = 'RADICADO_SMS_RETRY_REQUESTED';
    case RESPONSE_OBTAINED = 'RESPONSE_OBTAINED';
    case EXPORT_GENERATED = 'EXPORT_GENERATED';
}
