<?php

namespace App\Enums;

enum ImportRowReason: string
{
    case DUPLICATE_IN_FILE = 'DUPLICATE_IN_FILE';
    case RADICADO_NOT_AVAILABLE = 'RADICADO_NOT_AVAILABLE';
    case INVALID_RADICADO = 'INVALID_RADICADO';
    case INVALID_DATE = 'INVALID_DATE';
    case FUTURE_DATE = 'FUTURE_DATE';
    case MISSING_OBSERVATION = 'MISSING_OBSERVATION';
    case OBSERVATION_TOO_LONG = 'OBSERVATION_TOO_LONG';
    case ALREADY_RESPONDED = 'ALREADY_RESPONDED';
    case INVALID_ROW = 'INVALID_ROW';
}
